version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels: ["dependencies"]

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    labels: ["dependencies"]

  - package-ecosystem: npm
    directory: "/custom_components/home_keeper/frontend"
    schedule:
      interval: weekly
    labels: ["dependencies"]

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    labels: ["dependencies"]

  - package-ecosystem: npm
    directory: "/tests/e2e"
    schedule:
      interval: weekly
    labels: ["dependencies"]
