"""The task name of each duty an integration preset can track, per language.

Pure data, no Home Assistant import. declarative_presets.py builds each preset's
task_template.task_names from this table: the entity keys of a duty all map to
the duty's name. A task name is an action a person does, such as *Replace the
filter*, so it is not the entity's own name ("Filter time left").

Every duty has a name in the same 16 languages as backend_strings/. A test checks
that, so a new duty cannot ship in English only.
"""

from __future__ import annotations

DUTY_NAMES: dict[str, dict[str, str]] = {
    "annual_service": {
        "en": "Annual service",
        "ca": "Revisió anual",
        "cs": "Roční servis",
        "da": "Årligt eftersyn",
        "de": "Jährliche Wartung",
        "es": "Revisión anual",
        "fi": "Vuosihuolto",
        "fr": "Révision annuelle",
        "it": "Manutenzione annuale",
        "nb": "Årlig service",
        "nl": "Jaarlijks onderhoud",
        "pl": "Coroczny serwis",
        "pt-BR": "Revisão anual",
        "ru": "Ежегодное обслуживание",
        "sv": "Årlig service",
        "zh-Hans": "年度保养",
    },
    "bike_service": {
        "en": "Service the bike",
        "ca": "Revisar la bicicleta",
        "cs": "Servis kola",
        "da": "Servicér cyklen",
        "de": "Fahrrad warten",
        "es": "Revisar la bicicleta",
        "fi": "Huolla pyörä",
        "fr": "Réviser le vélo",
        "it": "Revisionare la bici",
        "nb": "Service på sykkelen",
        "nl": "Fiets onderhouden",
        "pl": "Serwis roweru",
        "pt-BR": "Revisar a bicicleta",
        "ru": "Обслужить велосипед",
        "sv": "Serva cykeln",
        "zh-Hans": "保养自行车",
    },
    "clean_appliance": {
        "en": "Clean the appliance",
        "ca": "Netejar l'aparell",
        "cs": "Vyčistit spotřebič",
        "da": "Rengør apparatet",
        "de": "Gerät reinigen",
        "es": "Limpiar el aparato",
        "fi": "Puhdista laite",
        "fr": "Nettoyer l'appareil",
        "it": "Pulire l'apparecchio",
        "nb": "Rengjør apparatet",
        "nl": "Apparaat reinigen",
        "pl": "Wyczyść urządzenie",
        "pt-BR": "Limpar o aparelho",
        "ru": "Очистить прибор",
        "sv": "Rengör apparaten",
        "zh-Hans": "清洁电器",
    },
    "clean_charging_contacts": {
        "en": "Clean the charging contacts",
        "ca": "Netejar els contactes de càrrega",
        "cs": "Vyčistit nabíjecí kontakty",
        "da": "Rengør ladekontakterne",
        "de": "Ladekontakte reinigen",
        "es": "Limpiar los contactos de carga",
        "fi": "Puhdista latauskoskettimet",
        "fr": "Nettoyer les contacts de charge",
        "it": "Pulire i contatti di ricarica",
        "nb": "Rengjør ladekontaktene",
        "nl": "Laadcontacten reinigen",
        "pl": "Wyczyść styki ładowania",
        "pt-BR": "Limpar os contatos de carga",
        "ru": "Очистить зарядные контакты",
        "sv": "Rengör laddkontakterna",
        "zh-Hans": "清洁充电触点",
    },
    "clean_grease_filter": {
        "en": "Clean the grease filter",
        "ca": "Netejar el filtre de greix",
        "cs": "Vyčistit tukový filtr",
        "da": "Rengør fedtfilteret",
        "de": "Fettfilter reinigen",
        "es": "Limpiar el filtro de grasa",
        "fi": "Puhdista rasvasuodatin",
        "fr": "Nettoyer le filtre à graisse",
        "it": "Pulire il filtro antigrasso",
        "nb": "Rengjør fettfilteret",
        "nl": "Vetfilter reinigen",
        "pl": "Wyczyść filtr przeciwtłuszczowy",
        "pt-BR": "Limpar o filtro de gordura",
        "ru": "Очистить жировой фильтр",
        "sv": "Rengör fettfiltret",
        "zh-Hans": "清洁油网",
    },
    "clean_mop_tray": {
        "en": "Clean the mop tray",
        "ca": "Netejar la safata de la mopa",
        "cs": "Vyčistit podložku mopu",
        "da": "Rengør mopbakken",
        "de": "Wischmopp-Schale reinigen",
        "es": "Limpiar la bandeja de la mopa",
        "fi": "Puhdista moppialusta",
        "fr": "Nettoyer le plateau de la serpillière",
        "it": "Pulire il vassoio del mocio",
        "nb": "Rengjør moppbrettet",
        "nl": "Dweilbak reinigen",
        "pl": "Wyczyść tacę mopa",
        "pt-BR": "Limpar a bandeja do esfregão",
        "ru": "Очистить поддон швабры",
        "sv": "Rengör moppbrickan",
        "zh-Hans": "清洁拖布托盘",
    },
    "clean_sensors": {
        "en": "Clean the sensors",
        "ca": "Netejar els sensors",
        "cs": "Vyčistit senzory",
        "da": "Rengør sensorerne",
        "de": "Sensoren reinigen",
        "es": "Limpiar los sensores",
        "fi": "Puhdista anturit",
        "fr": "Nettoyer les capteurs",
        "it": "Pulire i sensori",
        "nb": "Rengjør sensorene",
        "nl": "Sensoren reinigen",
        "pl": "Wyczyść czujniki",
        "pt-BR": "Limpar os sensores",
        "ru": "Очистить датчики",
        "sv": "Rengör sensorerna",
        "zh-Hans": "清洁传感器",
    },
    "clean_tub": {
        "en": "Clean the drum",
        "ca": "Netejar el tambor",
        "cs": "Vyčistit buben",
        "da": "Rengør tromlen",
        "de": "Trommel reinigen",
        "es": "Limpiar el tambor",
        "fi": "Puhdista rumpu",
        "fr": "Nettoyer le tambour",
        "it": "Pulire il cestello",
        "nb": "Rengjør trommelen",
        "nl": "Trommel reinigen",
        "pl": "Wyczyść bęben",
        "pt-BR": "Limpar o tambor",
        "ru": "Очистить барабан",
        "sv": "Rengör trumman",
        "zh-Hans": "清洁滚筒",
    },
    "condenser_cleaning": {
        "en": "Clean the condenser",
        "ca": "Netejar el condensador",
        "cs": "Vyčistit kondenzátor",
        "da": "Rengør kondensatoren",
        "de": "Kondensator reinigen",
        "es": "Limpiar el condensador",
        "fi": "Puhdista lauhdutin",
        "fr": "Nettoyer le condenseur",
        "it": "Pulire il condensatore",
        "nb": "Rengjør kondensatoren",
        "nl": "Condensor reinigen",
        "pl": "Wyczyść skraplacz",
        "pt-BR": "Limpar o condensador",
        "ru": "Очистить конденсатор",
        "sv": "Rengör kondensorn",
        "zh-Hans": "清洁冷凝器",
    },
    "descale_appliance": {
        "en": "Descale the appliance",
        "ca": "Descalcificar l'aparell",
        "cs": "Odvápnit spotřebič",
        "da": "Afkalk apparatet",
        "de": "Gerät entkalken",
        "es": "Descalcificar el aparato",
        "fi": "Poista kalkki laitteesta",
        "fr": "Détartrer l'appareil",
        "it": "Decalcificare l'apparecchio",
        "nb": "Avkalk apparatet",
        "nl": "Apparaat ontkalken",
        "pl": "Odkamień urządzenie",
        "pt-BR": "Descalcificar o aparelho",
        "ru": "Удалить накипь из прибора",
        "sv": "Avkalka apparaten",
        "zh-Hans": "为电器除垢",
    },
    "descaling": {
        "en": "Descale",
        "ca": "Descalcificar",
        "cs": "Odvápnit",
        "da": "Afkalk",
        "de": "Entkalken",
        "es": "Descalcificar",
        "fi": "Poista kalkki",
        "fr": "Détartrer",
        "it": "Decalcificare",
        "nb": "Avkalk",
        "nl": "Ontkalken",
        "pl": "Odkamień",
        "pt-BR": "Descalcificar",
        "ru": "Удалить накипь",
        "sv": "Avkalka",
        "zh-Hans": "除垢",
    },
    "empty_dirty_water_tank": {
        "en": "Empty the dirty water tank",
        "ca": "Buidar el dipòsit d'aigua bruta",
        "cs": "Vyprázdnit nádrž na špinavou vodu",
        "da": "Tøm beholderen til snavset vand",
        "de": "Schmutzwassertank leeren",
        "es": "Vaciar el depósito de agua sucia",
        "fi": "Tyhjennä likavesisäiliö",
        "fr": "Vider le réservoir d'eau sale",
        "it": "Svuotare il serbatoio dell'acqua sporca",
        "nb": "Tøm skittenvannstanken",
        "nl": "Vuilwatertank legen",
        "pl": "Opróżnij zbiornik na brudną wodę",
        "pt-BR": "Esvaziar o tanque de água suja",
        "ru": "Опустошить бак для грязной воды",
        "sv": "Töm smutsvattentanken",
        "zh-Hans": "清空污水箱",
    },
    "empty_dustbin": {
        "en": "Empty the dustbin",
        "ca": "Buidar el dipòsit de pols",
        "cs": "Vyprázdnit zásobník na prach",
        "da": "Tøm støvbeholderen",
        "de": "Staubbehälter leeren",
        "es": "Vaciar el depósito de polvo",
        "fi": "Tyhjennä pölysäiliö",
        "fr": "Vider le bac à poussière",
        "it": "Svuotare il contenitore della polvere",
        "nb": "Tøm støvbeholderen",
        "nl": "Stofbak legen",
        "pl": "Opróżnij pojemnik na kurz",
        "pt-BR": "Esvaziar o depósito de pó",
        "ru": "Опустошить пылесборник",
        "sv": "Töm dammbehållaren",
        "zh-Hans": "清空集尘盒",
    },
    "empty_waste_drawer": {
        "en": "Empty the waste drawer",
        "ca": "Buidar el calaix de residus",
        "cs": "Vyprázdnit zásuvku na odpad",
        "da": "Tøm affaldsskuffen",
        "de": "Abfallschublade leeren",
        "es": "Vaciar el cajón de residuos",
        "fi": "Tyhjennä jätelaatikko",
        "fr": "Vider le tiroir à déchets",
        "it": "Svuotare il cassetto dei rifiuti",
        "nb": "Tøm avfallsskuffen",
        "nl": "Afvallade legen",
        "pl": "Opróżnij szufladę na odpady",
        "pt-BR": "Esvaziar a gaveta de resíduos",
        "ru": "Опустошить ящик для отходов",
        "sv": "Töm avfallslådan",
        "zh-Hans": "清空废物抽屉",
    },
    "filter_cleaning": {
        "en": "Clean the filter",
        "ca": "Netejar el filtre",
        "cs": "Vyčistit filtr",
        "da": "Rengør filteret",
        "de": "Filter reinigen",
        "es": "Limpiar el filtro",
        "fi": "Puhdista suodatin",
        "fr": "Nettoyer le filtre",
        "it": "Pulire il filtro",
        "nb": "Rengjør filteret",
        "nl": "Filter reinigen",
        "pl": "Wyczyść filtr",
        "pt-BR": "Limpar o filtro",
        "ru": "Очистить фильтр",
        "sv": "Rengör filtret",
        "zh-Hans": "清洁滤网",
    },
    "lint_filter_cleaning": {
        "en": "Clean the lint filter",
        "ca": "Netejar el filtre de borrissol",
        "cs": "Vyčistit filtr na vlákna",
        "da": "Rengør fnugfilteret",
        "de": "Flusensieb reinigen",
        "es": "Limpiar el filtro de pelusa",
        "fi": "Puhdista nukkasihti",
        "fr": "Nettoyer le filtre à peluches",
        "it": "Pulire il filtro lanugine",
        "nb": "Rengjør lofilteret",
        "nl": "Pluizenfilter reinigen",
        "pl": "Wyczyść filtr kłaczków",
        "pt-BR": "Limpar o filtro de fiapos",
        "ru": "Очистить фильтр ворса",
        "sv": "Rengör luddfiltret",
        "zh-Hans": "清洁绒毛过滤器",
    },
    "oil_service": {
        "en": "Oil service",
        "ca": "Canvi d'oli",
        "cs": "Výměna oleje",
        "da": "Olieskift",
        "de": "Ölwechsel",
        "es": "Cambio de aceite",
        "fi": "Öljynvaihto",
        "fr": "Vidange",
        "it": "Cambio olio",
        "nb": "Oljeskift",
        "nl": "Olie verversen",
        "pl": "Wymiana oleju",
        "pt-BR": "Troca de óleo",
        "ru": "Замена масла",
        "sv": "Oljebyte",
        "zh-Hans": "更换机油",
    },
    "refill_detergent": {
        "en": "Refill the detergent",
        "ca": "Omplir el detergent",
        "cs": "Doplnit prací prostředek",
        "da": "Påfyld vaskemiddel",
        "de": "Waschmittel nachfüllen",
        "es": "Rellenar el detergente",
        "fi": "Lisää pesuainetta",
        "fr": "Remplir le détergent",
        "it": "Rabboccare il detersivo",
        "nb": "Fyll på vaskemiddel",
        "nl": "Wasmiddel bijvullen",
        "pl": "Uzupełnij detergent",
        "pt-BR": "Reabastecer o detergente",
        "ru": "Долить моющее средство",
        "sv": "Fyll på tvättmedel",
        "zh-Hans": "补充洗涤剂",
    },
    "refill_heating_water": {
        "en": "Top up the heating water",
        "ca": "Omplir l'aigua de la calefacció",
        "cs": "Doplnit vodu do topení",
        "da": "Påfyld vand i varmesystemet",
        "de": "Heizungswasser nachfüllen",
        "es": "Rellenar el agua de la calefacción",
        "fi": "Lisää vettä lämmitykseen",
        "fr": "Remettre de l'eau dans le chauffage",
        "it": "Rabboccare l'acqua del riscaldamento",
        "nb": "Fyll på vann i varmeanlegget",
        "nl": "Cv-water bijvullen",
        "pl": "Uzupełnij wodę w instalacji grzewczej",
        "pt-BR": "Completar a água do aquecimento",
        "ru": "Долить воду в систему отопления",
        "sv": "Fyll på vatten i värmesystemet",
        "zh-Hans": "补充采暖水",
    },
    "refill_litter": {
        "en": "Refill the litter",
        "ca": "Omplir la sorra",
        "cs": "Doplnit stelivo",
        "da": "Påfyld kattegrus",
        "de": "Streu nachfüllen",
        "es": "Rellenar la arena",
        "fi": "Lisää kissanhiekkaa",
        "fr": "Remettre de la litière",
        "it": "Rabboccare la lettiera",
        "nb": "Fyll på kattesand",
        "nl": "Kattenbakvulling bijvullen",
        "pl": "Uzupełnij żwirek",
        "pt-BR": "Reabastecer a areia",
        "ru": "Досыпать наполнитель",
        "sv": "Fyll på kattsand",
        "zh-Hans": "补充猫砂",
    },
    "refill_pool_salt": {
        "en": "Add pool salt",
        "ca": "Afegir sal a la piscina",
        "cs": "Doplnit sůl do bazénu",
        "da": "Tilsæt poolsalt",
        "de": "Poolsalz nachfüllen",
        "es": "Añadir sal a la piscina",
        "fi": "Lisää uima-altaan suolaa",
        "fr": "Ajouter du sel dans la piscine",
        "it": "Aggiungere sale in piscina",
        "nb": "Tilsett bassengsalt",
        "nl": "Zwembadzout bijvullen",
        "pl": "Dodaj sól do basenu",
        "pt-BR": "Adicionar sal à piscina",
        "ru": "Добавить соль в бассейн",
        "sv": "Tillsätt poolsalt",
        "zh-Hans": "补充泳池盐",
    },
    "refill_rinse_aid": {
        "en": "Refill the rinse aid",
        "ca": "Omplir l'abrillantador",
        "cs": "Doplnit leštidlo",
        "da": "Påfyld afspændingsmiddel",
        "de": "Klarspüler nachfüllen",
        "es": "Rellenar el abrillantador",
        "fi": "Lisää huuhtelukirkastetta",
        "fr": "Remplir le liquide de rinçage",
        "it": "Rabboccare il brillantante",
        "nb": "Fyll på skyllemiddel",
        "nl": "Glansspoelmiddel bijvullen",
        "pl": "Uzupełnij nabłyszczacz",
        "pt-BR": "Reabastecer o secante",
        "ru": "Долить ополаскиватель",
        "sv": "Fyll på sköljmedel",
        "zh-Hans": "补充漂洗剂",
    },
    "refill_salt": {
        "en": "Refill the salt",
        "ca": "Omplir la sal",
        "cs": "Doplnit sůl",
        "da": "Påfyld salt",
        "de": "Salz nachfüllen",
        "es": "Rellenar la sal",
        "fi": "Lisää suolaa",
        "fr": "Remplir le sel",
        "it": "Rabboccare il sale",
        "nb": "Fyll på salt",
        "nl": "Zout bijvullen",
        "pl": "Uzupełnij sól",
        "pt-BR": "Reabastecer o sal",
        "ru": "Досыпать соль",
        "sv": "Fyll på salt",
        "zh-Hans": "补充盐",
    },
    "refill_softener_salt": {
        "en": "Refill the softener salt",
        "ca": "Omplir la sal del descalcificador",
        "cs": "Doplnit sůl do změkčovače",
        "da": "Påfyld salt i blødgøringsanlægget",
        "de": "Enthärtersalz nachfüllen",
        "es": "Rellenar la sal del descalcificador",
        "fi": "Lisää pehmentimen suolaa",
        "fr": "Remplir le sel de l'adoucisseur",
        "it": "Rabboccare il sale dell'addolcitore",
        "nb": "Fyll på salt i avherderen",
        "nl": "Ontharderzout bijvullen",
        "pl": "Uzupełnij sól w zmiękczaczu",
        "pt-BR": "Reabastecer o sal do amaciador",
        "ru": "Досыпать соль в умягчитель",
        "sv": "Fyll på avhärdningssalt",
        "zh-Hans": "补充软水盐",
    },
    "replace_activated_carbon": {
        "en": "Replace the activated carbon",
        "ca": "Substituir el carbó actiu",
        "cs": "Vyměnit aktivní uhlí",
        "da": "Udskift det aktive kul",
        "de": "Aktivkohle ersetzen",
        "es": "Sustituir el carbón activo",
        "fi": "Vaihda aktiivihiili",
        "fr": "Remplacer le charbon actif",
        "it": "Sostituire il carbone attivo",
        "nb": "Bytt det aktive kullet",
        "nl": "Actieve kool vervangen",
        "pl": "Wymień węgiel aktywny",
        "pt-BR": "Substituir o carvão ativado",
        "ru": "Заменить активированный уголь",
        "sv": "Byt det aktiva kolet",
        "zh-Hans": "更换活性炭",
    },
    "replace_air_freshener": {
        "en": "Replace the air freshener",
        "ca": "Substituir l'ambientador",
        "cs": "Vyměnit osvěžovač vzduchu",
        "da": "Udskift luftfriskeren",
        "de": "Lufterfrischer ersetzen",
        "es": "Sustituir el ambientador",
        "fi": "Vaihda ilmanraikastin",
        "fr": "Remplacer le désodorisant",
        "it": "Sostituire il deodorante per ambienti",
        "nb": "Bytt luftfriskeren",
        "nl": "Luchtverfrisser vervangen",
        "pl": "Wymień odświeżacz powietrza",
        "pt-BR": "Substituir o aromatizador",
        "ru": "Заменить освежитель воздуха",
        "sv": "Byt luftfräschare",
        "zh-Hans": "更换空气清新剂",
    },
    "replace_belt_unit": {
        "en": "Replace the belt unit",
        "ca": "Substituir la unitat de corretja",
        "cs": "Vyměnit pásovou jednotku",
        "da": "Udskift bælteenheden",
        "de": "Transfereinheit ersetzen",
        "es": "Sustituir la unidad de correa",
        "fi": "Vaihda hihnayksikkö",
        "fr": "Remplacer l'unité de courroie",
        "it": "Sostituire l'unità nastro",
        "nb": "Bytt belteenheten",
        "nl": "Riemeenheid vervangen",
        "pl": "Wymień moduł pasa",
        "pt-BR": "Substituir a unidade de correia",
        "ru": "Заменить ленточный блок",
        "sv": "Byt bandenheten",
        "zh-Hans": "更换传送带单元",
    },
    "replace_blades": {
        "en": "Replace the blades",
        "ca": "Substituir les fulles",
        "cs": "Vyměnit nože",
        "da": "Udskift knivene",
        "de": "Messer ersetzen",
        "es": "Sustituir las cuchillas",
        "fi": "Vaihda terät",
        "fr": "Remplacer les lames",
        "it": "Sostituire le lame",
        "nb": "Bytt knivene",
        "nl": "Messen vervangen",
        "pl": "Wymień ostrza",
        "pt-BR": "Substituir as lâminas",
        "ru": "Заменить ножи",
        "sv": "Byt knivarna",
        "zh-Hans": "更换刀片",
    },
    "replace_brush_head": {
        "en": "Replace the brush head",
        "ca": "Substituir el capçal del raspall",
        "cs": "Vyměnit hlavici kartáčku",
        "da": "Udskift børstehovedet",
        "de": "Bürstenkopf ersetzen",
        "es": "Sustituir el cabezal del cepillo",
        "fi": "Vaihda harjaspää",
        "fr": "Remplacer la tête de brosse",
        "it": "Sostituire la testina",
        "nb": "Bytt børstehodet",
        "nl": "Opzetborstel vervangen",
        "pl": "Wymień końcówkę szczoteczki",
        "pt-BR": "Substituir a cabeça da escova",
        "ru": "Заменить насадку щётки",
        "sv": "Byt borsthuvudet",
        "zh-Hans": "更换刷头",
    },
    "replace_cleaning_cartridge": {
        "en": "Replace the cleaning cartridge",
        "ca": "Substituir el cartutx de neteja",
        "cs": "Vyměnit čisticí kazetu",
        "da": "Udskift rensepatronen",
        "de": "Reinigungskartusche ersetzen",
        "es": "Sustituir el cartucho de limpieza",
        "fi": "Vaihda puhdistuspatruuna",
        "fr": "Remplacer la cartouche de nettoyage",
        "it": "Sostituire la cartuccia di pulizia",
        "nb": "Bytt rensekassetten",
        "nl": "Reinigingspatroon vervangen",
        "pl": "Wymień wkład czyszczący",
        "pt-BR": "Substituir o cartucho de limpeza",
        "ru": "Заменить чистящий картридж",
        "sv": "Byt rengöringspatronen",
        "zh-Hans": "更换清洁盒",
    },
    "replace_cutting_disc": {
        "en": "Replace the cutting disc",
        "ca": "Substituir el disc de tall",
        "cs": "Vyměnit řezný kotouč",
        "da": "Udskift skæreskiven",
        "de": "Schneidscheibe ersetzen",
        "es": "Sustituir el disco de corte",
        "fi": "Vaihda leikkuulevy",
        "fr": "Remplacer le disque de coupe",
        "it": "Sostituire il disco di taglio",
        "nb": "Bytt kutteskiven",
        "nl": "Maaischijf vervangen",
        "pl": "Wymień tarczę tnącą",
        "pt-BR": "Substituir o disco de corte",
        "ru": "Заменить режущий диск",
        "sv": "Byt klippskivan",
        "zh-Hans": "更换切割盘",
    },
    "replace_desiccant": {
        "en": "Replace the desiccant",
        "ca": "Substituir el dessecant",
        "cs": "Vyměnit vysoušedlo",
        "da": "Udskift tørremidlet",
        "de": "Trockenmittel ersetzen",
        "es": "Sustituir el desecante",
        "fi": "Vaihda kuivausaine",
        "fr": "Remplacer le déshydratant",
        "it": "Sostituire il disidratante",
        "nb": "Bytt tørkemiddelet",
        "nl": "Droogmiddel vervangen",
        "pl": "Wymień pochłaniacz wilgoci",
        "pt-BR": "Substituir o dessecante",
        "ru": "Заменить влагопоглотитель",
        "sv": "Byt torkmedlet",
        "zh-Hans": "更换干燥剂",
    },
    "replace_dock_strainer": {
        "en": "Replace the dock strainer",
        "ca": "Substituir el filtre de la base",
        "cs": "Vyměnit sítko stanice",
        "da": "Udskift stationens si",
        "de": "Stationssieb ersetzen",
        "es": "Sustituir el filtro de la base",
        "fi": "Vaihda aseman siivilä",
        "fr": "Remplacer le filtre de la station",
        "it": "Sostituire il filtro della base",
        "nb": "Bytt stasjonens sil",
        "nl": "Stationszeef vervangen",
        "pl": "Wymień sitko stacji",
        "pt-BR": "Substituir o filtro da base",
        "ru": "Заменить сетку станции",
        "sv": "Byt stationens sil",
        "zh-Hans": "更换基站滤网",
    },
    "replace_drum_unit": {
        "en": "Replace the drum unit",
        "ca": "Substituir la unitat de tambor",
        "cs": "Vyměnit válcovou jednotku",
        "da": "Udskift tromleenheden",
        "de": "Trommeleinheit ersetzen",
        "es": "Sustituir la unidad de tambor",
        "fi": "Vaihda rumpuyksikkö",
        "fr": "Remplacer l'unité tambour",
        "it": "Sostituire il tamburo",
        "nb": "Bytt trommelenheten",
        "nl": "Drumeenheid vervangen",
        "pl": "Wymień bęben",
        "pt-BR": "Substituir a unidade de cilindro",
        "ru": "Заменить фотобарабан",
        "sv": "Byt trumenheten",
        "zh-Hans": "更换硒鼓单元",
    },
    "replace_dust_bag": {
        "en": "Replace the dust bag",
        "ca": "Substituir la bossa de pols",
        "cs": "Vyměnit sáček na prach",
        "da": "Udskift støvposen",
        "de": "Staubbeutel ersetzen",
        "es": "Sustituir la bolsa de polvo",
        "fi": "Vaihda pölypussi",
        "fr": "Remplacer le sac à poussière",
        "it": "Sostituire il sacchetto della polvere",
        "nb": "Bytt støvposen",
        "nl": "Stofzak vervangen",
        "pl": "Wymień worek na kurz",
        "pt-BR": "Substituir o saco de pó",
        "ru": "Заменить пылесборный мешок",
        "sv": "Byt dammpåsen",
        "zh-Hans": "更换集尘袋",
    },
    "replace_edge_trimmer_blade": {
        "en": "Replace the edge trimmer blade",
        "ca": "Substituir la fulla del perfilador",
        "cs": "Vyměnit nůž ořezávače okrajů",
        "da": "Udskift kantklipperens kniv",
        "de": "Kantenschneider-Messer ersetzen",
        "es": "Sustituir la cuchilla del perfilador",
        "fi": "Vaihda reunaleikkurin terä",
        "fr": "Remplacer la lame du coupe-bordure",
        "it": "Sostituire la lama del rifinitore",
        "nb": "Bytt kantklipperens kniv",
        "nl": "Kantmaaiermes vervangen",
        "pl": "Wymień ostrze podkaszarki",
        "pt-BR": "Substituir a lâmina do aparador de bordas",
        "ru": "Заменить нож кромкореза",
        "sv": "Byt kantklipparens kniv",
        "zh-Hans": "更换修边刀片",
    },
    "replace_edge_trimmer_disc": {
        "en": "Replace the edge trimmer disc",
        "ca": "Substituir el disc del perfilador",
        "cs": "Vyměnit kotouč ořezávače okrajů",
        "da": "Udskift kantklipperens skive",
        "de": "Kantenschneider-Scheibe ersetzen",
        "es": "Sustituir el disco del perfilador",
        "fi": "Vaihda reunaleikkurin levy",
        "fr": "Remplacer le disque du coupe-bordure",
        "it": "Sostituire il disco del rifinitore",
        "nb": "Bytt kantklipperens skive",
        "nl": "Kantmaaierschijf vervangen",
        "pl": "Wymień tarczę podkaszarki",
        "pt-BR": "Substituir o disco do aparador de bordas",
        "ru": "Заменить диск кромкореза",
        "sv": "Byt kantklipparens skiva",
        "zh-Hans": "更换修边盘",
    },
    "replace_filter": {
        "en": "Replace the filter",
        "ca": "Substituir el filtre",
        "cs": "Vyměnit filtr",
        "da": "Udskift filteret",
        "de": "Filter ersetzen",
        "es": "Sustituir el filtro",
        "fi": "Vaihda suodatin",
        "fr": "Remplacer le filtre",
        "it": "Sostituire il filtro",
        "nb": "Bytt filteret",
        "nl": "Filter vervangen",
        "pl": "Wymień filtr",
        "pt-BR": "Substituir o filtro",
        "ru": "Заменить фильтр",
        "sv": "Byt filtret",
        "zh-Hans": "更换滤网",
    },
    "replace_fuser": {
        "en": "Replace the fuser",
        "ca": "Substituir el fusor",
        "cs": "Vyměnit zapékací jednotku",
        "da": "Udskift fikseringsenheden",
        "de": "Fixiereinheit ersetzen",
        "es": "Sustituir el fusor",
        "fi": "Vaihda kiinnitysyksikkö",
        "fr": "Remplacer l'unité de fusion",
        "it": "Sostituire il fusore",
        "nb": "Bytt fikseringsenheten",
        "nl": "Fuser vervangen",
        "pl": "Wymień utrwalacz",
        "pt-BR": "Substituir o fusor",
        "ru": "Заменить термоблок",
        "sv": "Byt fixeringsenheten",
        "zh-Hans": "更换定影器",
    },
    "replace_ink_or_toner": {
        "en": "Replace the ink or toner",
        "ca": "Substituir la tinta o el tòner",
        "cs": "Vyměnit inkoust nebo toner",
        "da": "Udskift blæk eller toner",
        "de": "Tinte oder Toner ersetzen",
        "es": "Sustituir la tinta o el tóner",
        "fi": "Vaihda muste tai väriaine",
        "fr": "Remplacer l'encre ou le toner",
        "it": "Sostituire inchiostro o toner",
        "nb": "Bytt blekk eller toner",
        "nl": "Inkt of toner vervangen",
        "pl": "Wymień tusz lub toner",
        "pt-BR": "Substituir a tinta ou o toner",
        "ru": "Заменить чернила или тонер",
        "sv": "Byt bläck eller toner",
        "zh-Hans": "更换墨水或碳粉",
    },
    "replace_laser_unit": {
        "en": "Replace the laser unit",
        "ca": "Substituir la unitat làser",
        "cs": "Vyměnit laserovou jednotku",
        "da": "Udskift laserenheden",
        "de": "Lasereinheit ersetzen",
        "es": "Sustituir la unidad láser",
        "fi": "Vaihda laseryksikkö",
        "fr": "Remplacer l'unité laser",
        "it": "Sostituire l'unità laser",
        "nb": "Bytt laserenheten",
        "nl": "Lasereenheid vervangen",
        "pl": "Wymień moduł lasera",
        "pt-BR": "Substituir a unidade de laser",
        "ru": "Заменить лазерный блок",
        "sv": "Byt laserenheten",
        "zh-Hans": "更换激光单元",
    },
    "replace_lens_brush": {
        "en": "Replace the lens brush",
        "ca": "Substituir el raspall de la lent",
        "cs": "Vyměnit kartáček čočky",
        "da": "Udskift linsebørsten",
        "de": "Linsenbürste ersetzen",
        "es": "Sustituir el cepillo de la lente",
        "fi": "Vaihda linssiharja",
        "fr": "Remplacer la brosse de l'objectif",
        "it": "Sostituire la spazzola della lente",
        "nb": "Bytt linsebørsten",
        "nl": "Lensborstel vervangen",
        "pl": "Wymień szczoteczkę soczewki",
        "pt-BR": "Substituir a escova da lente",
        "ru": "Заменить щётку объектива",
        "sv": "Byt linsborsten",
        "zh-Hans": "更换镜头刷",
    },
    "replace_main_brush": {
        "en": "Replace the main brush",
        "ca": "Substituir el raspall principal",
        "cs": "Vyměnit hlavní kartáč",
        "da": "Udskift hovedbørsten",
        "de": "Hauptbürste ersetzen",
        "es": "Sustituir el cepillo principal",
        "fi": "Vaihda pääharja",
        "fr": "Remplacer la brosse principale",
        "it": "Sostituire la spazzola principale",
        "nb": "Bytt hovedbørsten",
        "nl": "Hoofdborstel vervangen",
        "pl": "Wymień szczotkę główną",
        "pt-BR": "Substituir a escova principal",
        "ru": "Заменить основную щётку",
        "sv": "Byt huvudborsten",
        "zh-Hans": "更换主刷",
    },
    "replace_maintenance_box": {
        "en": "Replace the maintenance box",
        "ca": "Substituir la caixa de manteniment",
        "cs": "Vyměnit údržbovou kazetu",
        "da": "Udskift vedligeholdelsesboksen",
        "de": "Wartungsbox ersetzen",
        "es": "Sustituir la caja de mantenimiento",
        "fi": "Vaihda huoltolaatikko",
        "fr": "Remplacer le boîtier de maintenance",
        "it": "Sostituire il contenitore di manutenzione",
        "nb": "Bytt vedlikeholdsboksen",
        "nl": "Onderhoudscassette vervangen",
        "pl": "Wymień pojemnik konserwacyjny",
        "pt-BR": "Substituir a caixa de manutenção",
        "ru": "Заменить контейнер для отработанных чернил",
        "sv": "Byt underhållsboxen",
        "zh-Hans": "更换维护箱",
    },
    "replace_maintenance_brush": {
        "en": "Replace the maintenance brush",
        "ca": "Substituir el raspall de manteniment",
        "cs": "Vyměnit čisticí kartáč",
        "da": "Udskift rensebørsten",
        "de": "Reinigungsbürste ersetzen",
        "es": "Sustituir el cepillo de mantenimiento",
        "fi": "Vaihda huoltoharja",
        "fr": "Remplacer la brosse d'entretien",
        "it": "Sostituire la spazzola di manutenzione",
        "nb": "Bytt rengjøringsbørsten",
        "nl": "Onderhoudsborstel vervangen",
        "pl": "Wymień szczotkę czyszczącą",
        "pt-BR": "Substituir a escova de manutenção",
        "ru": "Заменить чистящую щётку",
        "sv": "Byt rengöringsborsten",
        "zh-Hans": "更换清洁刷",
    },
    "replace_mop_pads": {
        "en": "Replace the mop pads",
        "ca": "Substituir les baietes",
        "cs": "Vyměnit mopovací podložky",
        "da": "Udskift moppepuderne",
        "de": "Wischpads ersetzen",
        "es": "Sustituir las mopas",
        "fi": "Vaihda moppityynyt",
        "fr": "Remplacer les lingettes",
        "it": "Sostituire i panni",
        "nb": "Bytt moppeputene",
        "nl": "Dweilpads vervangen",
        "pl": "Wymień nakładki mopa",
        "pt-BR": "Substituir os panos",
        "ru": "Заменить салфетки швабры",
        "sv": "Byt moppdynorna",
        "zh-Hans": "更换拖布",
    },
    "replace_odor_eliminator": {
        "en": "Replace the odor eliminator",
        "ca": "Substituir l'eliminador d'olors",
        "cs": "Vyměnit pohlcovač pachů",
        "da": "Udskift lugtfjerneren",
        "de": "Geruchsneutralisierer ersetzen",
        "es": "Sustituir el eliminador de olores",
        "fi": "Vaihda hajunpoistaja",
        "fr": "Remplacer le désodorisant",
        "it": "Sostituire l'eliminatore di odori",
        "nb": "Bytt luktfjerneren",
        "nl": "Geurverwijderaar vervangen",
        "pl": "Wymień pochłaniacz zapachów",
        "pt-BR": "Substituir o eliminador de odores",
        "ru": "Заменить поглотитель запахов",
        "sv": "Byt luktborttagaren",
        "zh-Hans": "更换除味剂",
    },
    "replace_paper_feed_kit": {
        "en": "Replace the paper feed kit",
        "ca": "Substituir el kit d'alimentació de paper",
        "cs": "Vyměnit sadu podavače papíru",
        "da": "Udskift papirfødningssættet",
        "de": "Papiereinzugskit ersetzen",
        "es": "Sustituir el kit de alimentación de papel",
        "fi": "Vaihda paperinsyöttösarja",
        "fr": "Remplacer le kit d'alimentation papier",
        "it": "Sostituire il kit di alimentazione carta",
        "nb": "Bytt papirmatesettet",
        "nl": "Papierinvoerset vervangen",
        "pl": "Wymień zestaw podawania papieru",
        "pt-BR": "Substituir o kit de alimentação de papel",
        "ru": "Заменить комплект подачи бумаги",
        "sv": "Byt pappersmatningssatsen",
        "zh-Hans": "更换进纸套件",
    },
    "replace_salt_cartridge": {
        "en": "Replace the salt cartridge",
        "ca": "Substituir el cartutx de sal",
        "cs": "Vyměnit solnou kazetu",
        "da": "Udskift saltpatronen",
        "de": "Salzkartusche ersetzen",
        "es": "Sustituir el cartucho de sal",
        "fi": "Vaihda suolapatruuna",
        "fr": "Remplacer la cartouche de sel",
        "it": "Sostituire la cartuccia del sale",
        "nb": "Bytt saltpatronen",
        "nl": "Zoutpatroon vervangen",
        "pl": "Wymień wkład solny",
        "pt-BR": "Substituir o cartucho de sal",
        "ru": "Заменить солевой картридж",
        "sv": "Byt saltpatronen",
        "zh-Hans": "更换盐盒",
    },
    "replace_shaver_head": {
        "en": "Replace the shaver head",
        "ca": "Substituir el capçal de l'afaitadora",
        "cs": "Vyměnit holicí hlavu",
        "da": "Udskift skærehovedet",
        "de": "Scherkopf ersetzen",
        "es": "Sustituir el cabezal de la afeitadora",
        "fi": "Vaihda ajopää",
        "fr": "Remplacer la tête de rasoir",
        "it": "Sostituire la testina del rasoio",
        "nb": "Bytt skjærehodet",
        "nl": "Scheerkop vervangen",
        "pl": "Wymień głowicę golarki",
        "pt-BR": "Substituir a cabeça do barbeador",
        "ru": "Заменить бритвенную головку",
        "sv": "Byt rakhuvudet",
        "zh-Hans": "更换剃须刀头",
    },
    "replace_side_brush": {
        "en": "Replace the side brush",
        "ca": "Substituir el raspall lateral",
        "cs": "Vyměnit boční kartáč",
        "da": "Udskift sidebørsten",
        "de": "Seitenbürste ersetzen",
        "es": "Sustituir el cepillo lateral",
        "fi": "Vaihda sivuharja",
        "fr": "Remplacer la brosse latérale",
        "it": "Sostituire la spazzola laterale",
        "nb": "Bytt sidebørsten",
        "nl": "Zijborstel vervangen",
        "pl": "Wymień szczotkę boczną",
        "pt-BR": "Substituir a escova lateral",
        "ru": "Заменить боковую щётку",
        "sv": "Byt sidoborsten",
        "zh-Hans": "更换边刷",
    },
    "replace_toner": {
        "en": "Replace the toner",
        "ca": "Substituir el tòner",
        "cs": "Vyměnit toner",
        "da": "Udskift toneren",
        "de": "Toner ersetzen",
        "es": "Sustituir el tóner",
        "fi": "Vaihda väriaine",
        "fr": "Remplacer le toner",
        "it": "Sostituire il toner",
        "nb": "Bytt toneren",
        "nl": "Toner vervangen",
        "pl": "Wymień toner",
        "pt-BR": "Substituir o toner",
        "ru": "Заменить тонер",
        "sv": "Byt tonern",
        "zh-Hans": "更换碳粉",
    },
    "replace_trimmer_brush": {
        "en": "Replace the trimmer brush",
        "ca": "Substituir el raspall de vores",
        "cs": "Vyměnit okrajový kartáč",
        "da": "Udskift kantbørsten",
        "de": "Kantenbürste ersetzen",
        "es": "Sustituir el cepillo de bordes",
        "fi": "Vaihda reunaharja",
        "fr": "Remplacer la brosse de bordure",
        "it": "Sostituire la spazzola per bordi",
        "nb": "Bytt kantbørsten",
        "nl": "Randborstel vervangen",
        "pl": "Wymień szczotkę krawędziową",
        "pt-BR": "Substituir a escova de bordas",
        "ru": "Заменить кромочную щётку",
        "sv": "Byt kantborsten",
        "zh-Hans": "更换修边刷",
    },
    "replace_trimmer_line": {
        "en": "Replace the trimmer line",
        "ca": "Substituir el fil del desbrossador",
        "cs": "Vyměnit strunu vyžínače",
        "da": "Udskift trimmertråden",
        "de": "Trimmerfaden ersetzen",
        "es": "Sustituir el hilo de la desbrozadora",
        "fi": "Vaihda trimmerin siima",
        "fr": "Remplacer le fil du coupe-bordure",
        "it": "Sostituire il filo del tagliabordi",
        "nb": "Bytt trimmertråden",
        "nl": "Trimmerdraad vervangen",
        "pl": "Wymień żyłkę podkaszarki",
        "pt-BR": "Substituir o fio do aparador",
        "ru": "Заменить леску триммера",
        "sv": "Byt trimmertråden",
        "zh-Hans": "更换割草线",
    },
    "replace_uv_lamp": {
        "en": "Replace the UV lamp",
        "ca": "Substituir la làmpada UV",
        "cs": "Vyměnit UV lampu",
        "da": "Udskift UV-lampen",
        "de": "UV-Lampe ersetzen",
        "es": "Sustituir la lámpara UV",
        "fi": "Vaihda UV-lamppu",
        "fr": "Remplacer la lampe UV",
        "it": "Sostituire la lampada UV",
        "nb": "Bytt UV-lampen",
        "nl": "Uv-lamp vervangen",
        "pl": "Wymień lampę UV",
        "pt-BR": "Substituir a lâmpada UV",
        "ru": "Заменить УФ-лампу",
        "sv": "Byt UV-lampan",
        "zh-Hans": "更换紫外线灯",
    },
    "replace_ventilation_filter": {
        "en": "Replace the ventilation filter",
        "ca": "Substituir el filtre de ventilació",
        "cs": "Vyměnit filtr větrání",
        "da": "Udskift ventilationsfilteret",
        "de": "Lüftungsfilter ersetzen",
        "es": "Sustituir el filtro de ventilación",
        "fi": "Vaihda ilmanvaihdon suodatin",
        "fr": "Remplacer le filtre de ventilation",
        "it": "Sostituire il filtro di ventilazione",
        "nb": "Bytt ventilasjonsfilteret",
        "nl": "Ventilatiefilter vervangen",
        "pl": "Wymień filtr wentylacji",
        "pt-BR": "Substituir o filtro de ventilação",
        "ru": "Заменить фильтр вентиляции",
        "sv": "Byt ventilationsfiltret",
        "zh-Hans": "更换通风滤网",
    },
    "replace_water_filter": {
        "en": "Replace the water filter",
        "ca": "Substituir el filtre d'aigua",
        "cs": "Vyměnit vodní filtr",
        "da": "Udskift vandfilteret",
        "de": "Wasserfilter ersetzen",
        "es": "Sustituir el filtro de agua",
        "fi": "Vaihda vedensuodatin",
        "fr": "Remplacer le filtre à eau",
        "it": "Sostituire il filtro dell'acqua",
        "nb": "Bytt vannfilteret",
        "nl": "Waterfilter vervangen",
        "pl": "Wymień filtr wody",
        "pt-BR": "Substituir o filtro de água",
        "ru": "Заменить фильтр для воды",
        "sv": "Byt vattenfiltret",
        "zh-Hans": "更换滤水器",
    },
    "replace_wick": {
        "en": "Replace the wick",
        "ca": "Substituir la metxa",
        "cs": "Vyměnit knot",
        "da": "Udskift vægen",
        "de": "Verdunstungsdocht ersetzen",
        "es": "Sustituir la mecha",
        "fi": "Vaihda sydän",
        "fr": "Remplacer la mèche",
        "it": "Sostituire lo stoppino",
        "nb": "Bytt veken",
        "nl": "Verdampingslont vervangen",
        "pl": "Wymień knot",
        "pt-BR": "Substituir o pavio",
        "ru": "Заменить фитиль",
        "sv": "Byt veken",
        "zh-Hans": "更换加湿芯",
    },
    "storage_cleanup": {
        "en": "Free up storage",
        "ca": "Alliberar emmagatzematge",
        "cs": "Uvolnit úložiště",
        "da": "Frigør lagerplads",
        "de": "Speicher freigeben",
        "es": "Liberar almacenamiento",
        "fi": "Vapauta tallennustilaa",
        "fr": "Libérer de l'espace de stockage",
        "it": "Liberare spazio di archiviazione",
        "nb": "Frigjør lagringsplass",
        "nl": "Opslag vrijmaken",
        "pl": "Zwolnij miejsce na dysku",
        "pt-BR": "Liberar armazenamento",
        "ru": "Освободить место на накопителе",
        "sv": "Frigör lagringsutrymme",
        "zh-Hans": "释放存储空间",
    },
    "water_test": {
        "en": "Test the water",
        "ca": "Analitzar l'aigua",
        "cs": "Otestovat vodu",
        "da": "Test vandet",
        "de": "Wasser testen",
        "es": "Analizar el agua",
        "fi": "Testaa vesi",
        "fr": "Tester l'eau",
        "it": "Analizzare l'acqua",
        "nb": "Test vannet",
        "nl": "Water testen",
        "pl": "Zbadaj wodę",
        "pt-BR": "Testar a água",
        "ru": "Проверить воду",
        "sv": "Testa vattnet",
        "zh-Hans": "检测水质",
    },
}
